@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "id.ac.ui.cs.advprog.productservice.controller.ProductRestController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_3106 { 
   	label=ac
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_92578784 { 
   	label=ui
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ProductRestController767523206[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProductRestController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productService: ProductService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tagService: TagService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createProduct(product: Product, tagNames: String): ResponseEntity</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteProduct(productId: String): ResponseEntity</TD></TR>
<TR><TD ALIGN="LEFT" >+ editProduct(product: Product, tagNames: String): ResponseEntity</TD></TR>
<TR><TD ALIGN="LEFT" >+ getProductById(id: String): ResponseEntity</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ProductServiceImpl253397259[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProductServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   productRepository: ProductRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create(product: Product): Product</TD></TR>
<TR><TD ALIGN="LEFT" >+ delete(id: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Product&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findById(id: String): Product</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(product: Product): Product</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TagServiceImpl253397259[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TagServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   tagRepository: TagRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create(tag: Tag): Tag</TD></TR>
<TR><TD ALIGN="LEFT" >+ delete(id: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Tag&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findById(id: String): Tag</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByName(name: String): Tag</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ProductRestController767523206 -> ProductServiceImpl253397259[arrowhead=none];
ProductRestController767523206 -> TagServiceImpl253397259[arrowhead=none];
    
}
@enduml